version: "3"

services:
  gui:
    build:
      context: ../src/gui
    container_name: testbench-gui
    ports:
      - "3000:3000"
    depends_on:
      - producer
    networks:
      - private_network
  producer_queue:
    build:
      context: ../src/rabbitmq
    container_name: producer-queue
    ports:
      - "5679:5672"
      - "15679:15672"
    networks:
      - private_network
  broker_queue:
    build:
      context: ../src/rabbitmq
    container_name: broker-queue
    hostname: broker-queue
    ports:
      - "5675:5672"
      - "15675:15672"
    networks:
      - private_network
  producer:
    build:
      context: ../src/producer/
    container_name: producer
    ports:
      - "8080:8080"
    depends_on:
      - producer_queue
      - relational_database
    networks:
      - private_network
  broker:
    build:
      context: ../src/broker/
    container_name: broker
    ports:
      - "8081:8081"
    depends_on:
      - broker_queue
      - relational_database
    networks:
      - private_network
  worker_0:
    build:
      context: ../src/worker/
    command: "--worker.id=0"
    container_name: worker-0
    ports:
      - "8500:8500"
    depends_on:
      - workers_queue
      - relational_database
    networks:
      - private_network
  worker_1:
    build:
      context: ../src/worker/
    command: "--worker.id=1"
    container_name: worker-1
    depends_on:
      - workers_queue
      - relational_database
    networks:
      - private_network
  worker_2:
    build:
      context: ../src/worker/
    command: "--worker.id=2"
    container_name: worker-2
    depends_on:
      - workers_queue
      - relational_database
    networks:
      - private_network
  worker_3:
    build:
      context: ../src/worker/
    command: "--worker.id=3"
    container_name: worker-3
    depends_on:
      - workers_queue
      - relational_database
    networks:
      - private_network
  worker_4:
    build:
      context: ../src/worker/
    command: "--worker.id=4"
    container_name: worker-4
    depends_on:
      - workers_queue
      - relational_database
    networks:
      - private_network
  worker_5:
    build:
      context: ../src/worker/
    command: "--worker.id=5"
    container_name: worker-5
    depends_on:
      - workers_queue
      - relational_database
    networks:
      - private_network
  worker_6:
    build:
      context: ../src/worker/
    command: "--worker.id=6"
    container_name: worker-6
    depends_on:
      - workers_queue
      - relational_database
    networks:
      - private_network
  worker_7:
    build:
      context: ../src/worker/
    command: "--worker.id=7"
    container_name: worker-7
    depends_on:
      - workers_queue
      - relational_database
    networks:
      - private_network
  olt_0:
    build:
      context: ../src/olt/
    command: "--olt.id=0"
    container_name: olt-0
    depends_on:
      - olts_queue
    networks:
      - private_network
  olt_1:
    build:
      context: ../src/olt/
    command: "--olt.id=1"
    container_name: olt-1
    depends_on:
      - olts_queue
    networks:
      - private_network
  olt_2:
    build:
      context: ../src/olt/
    command: "--olt.id=2"
    container_name: olt-2
    depends_on:
      - olts_queue
    networks:
      - private_network
  olt_3:
    build:
      context: ../src/olt/
    command: "--olt.id=3"
    container_name: olt-3
    depends_on:
      - olts_queue
    networks:
      - private_network
  olt_4:
    build:
      context: ../src/olt/
    command: "--olt.id=4"
    container_name: olt-4
    depends_on:
      - olts_queue
    networks:
      - private_network
  olt_5:
    build:
      context: ../src/olt/
    command: "--olt.id=5"
    container_name: olt-5
    depends_on:
      - olts_queue
    networks:
      - private_network
  olt_6:
    build:
      context: ../src/olt/
    command: "--olt.id=6"
    container_name: olt-6
    depends_on:
      - olts_queue
    networks:
      - private_network
  olt_7:
    build:
      context: ../src/olt/
    command: "--olt.id=7"
    container_name: olt-7
    depends_on:
      - olts_queue
    networks:
      - private_network
  workers_queue:
    build:
      context: ../src/rabbitmq
    container_name: workers-queue
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - private_network
  olts_queue:
    build:
      context: ../src/rabbitmq
    container_name: olts-queue
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - private_network
  relational_database:
    build:
      context: ../src/run_results_database/
    container_name: relational-db
    ports:
      - "5432:5432"
    networks:
      - private_network
networks:
  private_network:
    driver: bridge
