version: "3"

services:
  producer_queue:
    image: rabbitmq:3.9.13-management
    container_name: producer-queue
    ports:
      - "5679:5672"
      - "15679:15672"
    networks:
      - private_network
  broker_queue:
    image: rabbitmq:3.9.13-management
    container_name: broker-queue
    hostname: broker-queue
    ports:
      - "5675:5672"
      - "15675:15672"
    networks:
      - private_network
  producer:
    build:
      context: ../src/producer/
    container_name: producer
    ports:
      - "8080:8080"
    depends_on:
      - producer_queue
      - relational_database
    networks:
      - private_network
  broker:
    build:
      context: ../src/broker/
    container_name: broker
    depends_on:
      - broker_queue
      - relational_database
    networks:
      - private_network
  worker_0:
    build:
      context: ../src/worker/
    command: "--server.port=8500 --spring.rabbitmq.host=worker-queue-0 --worker.id=0"
    container_name: worker-0
    depends_on:
      - worker_queue_0
      - relational_database
    networks:
      - private_network
  worker_1:
    build:
      context: ../src/worker/
    command: "--server.port=8501 --spring.rabbitmq.host=worker-queue-1 --worker.id=1"
    container_name: worker-1
    depends_on:
      - worker_queue_1
      - relational_database
    networks:
      - private_network
  worker_2:
    build:
      context: ../src/worker/
    command: "--server.port=8502 --spring.rabbitmq.host=worker-queue-2 --worker.id=2"
    container_name: worker-2
    depends_on:
      - worker_queue_2
      - relational_database
    networks:
      - private_network
  olt_0:
    build:
      context: ../src/olt/
    command: "--server.port=9000 --spring.rabbitmq.host=olt-queue-0"
    container_name: olt-0
    depends_on:
      - olt_queue_0
    networks:
      - private_network
  olt_1:
    build:
      context: ../src/olt/
    command: "--server.port=9001 --spring.rabbitmq.host=olt-queue-1"
    container_name: olt-1
    depends_on:
      - olt_queue_1
    networks:
      - private_network
  olt_2:
    build:
      context: ../src/olt/
    command: "--server.port=9002 --spring.rabbitmq.host=olt-queue-2"
    container_name: olt-2
    depends_on:
      - olt_queue_2
    networks:
      - private_network
  olt_3:
    build:
      context: ../src/olt/
    command: "--server.port=9003 --spring.rabbitmq.host=olt-queue-3"
    container_name: olt-3
    depends_on:
      - olt_queue_3
    networks:
      - private_network
  olt_4:
    build:
      context: ../src/olt/
    command: "--server.port=9004 --spring.rabbitmq.host=olt-queue-4"
    container_name: olt-4
    depends_on:
      - olt_queue_4
    networks:
      - private_network
  worker_queue_0:
    image: rabbitmq:3.9.13-management
    container_name: worker-queue-0
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - private_network
  worker_queue_1:
    image: rabbitmq:3.9.13-management
    container_name: worker-queue-1
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - private_network
  worker_queue_2:
    image: rabbitmq:3.9.13-management
    container_name: worker-queue-2
    ports:
      - "5674:5672"
      - "15674:15672"
    networks:
      - private_network
  olt_queue_0:
    image: rabbitmq:3.9.13-management
    container_name: olt-queue-0
    ports:
      - "5676:5672"
      - "15676:15672"
    networks:
      - private_network
  olt_queue_1:
    image: rabbitmq:3.9.13-management
    container_name: olt-queue-1
    ports:
      - "5677:5672"
      - "15677:15672"
    networks:
      - private_network
  olt_queue_2:
    image: rabbitmq:3.9.13-management
    container_name: olt-queue-2
    ports:
      - "5678:5672"
      - "15678:15672"
    networks:
      - private_network
  olt_queue_3:
    image: rabbitmq:3.9.13-management
    container_name: olt-queue-3
    ports:
      - "5680:5672"
      - "15680:15672"
    networks:
      - private_network
  olt_queue_4:
    image: rabbitmq:3.9.13-management
    container_name: olt-queue-4
    ports:
      - "5681:5672"
      - "15681:15672"
    networks:
      - private_network
  relational_database:
    build:
      context: ../src/run_results_database/
    container_name: relational-db
    ports:
      - "5432:5432"
    networks:
      - private_network
networks:
  private_network:
    driver: bridge
