name: uservice_arch_testbench
root: <%= ENV["PWD"] %>

startup_window: producer

windows:
  - producer:
      layout: main-vertical
      panes:
        - app:
            - cd ~/Code/uservice_arch_testbench
            - cd producer_spring
            - mvn spring-boot:run -Dspring-boot.run.arguments="--sever.port=8080 --spring.rabbitmq.port=5679"
  - broker:
      layout: main-vertical
      panes:
        - app:
            - cd ~/Code/uservice_arch_testbench
            - cd broker_spring
            - mvn spring-boot:run -Dspring-boot.run.arguments="--server.port=8081 --spring.rabbitmq.port=5675"
  - worker_id_0:
      layout: main-vertical
      panes:
        - app:
            - cd ~/Code/uservice_arch_testbench
            - cd worker_spring
            - mvn spring-boot:run -Dspring-boot.run.arguments="--worker.id=0 --server.port=8500 --spring.rabbitmq.port=5672"
  - worker_id_1:
      layout: main-vertical
      panes:
        - app:
            - cd ~/Code/uservice_arch_testbench
            - cd worker_spring
            - mvn spring-boot:run -Dspring-boot.run.arguments="--worker.id=1 --server.port=8501 --spring.rabbitmq.port=5673"
  - worker_id_2:
      layout: main-vertical
      panes:
        - app:
            - cd ~/Code/uservice_arch_testbench
            - cd worker_spring
            - mvn spring-boot:run -Dspring-boot.run.arguments="--worker.id=2 --server.port=8502 --spring.rabbitmq.port=5674"
  - olt_0:
      layout: main-vertical
      panes:
        - app:
            - cd ~/Code/uservice_arch_testbench
            - cd olt_spring
            - mvn spring-boot:run -Dspring-boot.run.arguments="--server.port=9000 --spring.rabbitmq.port=5676"
  - olt_1:
      layout: main-vertical
      panes:
        - app:
            - cd ~/Code/uservice_arch_testbench
            - cd olt_spring
            - mvn spring-boot:run -Dspring-boot.run.arguments="--server.port=9001 --spring.rabbitmq.port=5677"
  - olt_2:
      layout: main-vertical
      panes:
        - app:
            - cd ~/Code/uservice_arch_testbench
            - cd olt_spring
            - mvn spring-boot:run -Dspring-boot.run.arguments="--server.port=9002 --spring.rabbitmq.port=5678"
