version: "3"

services:
  producer_orchestration_queue:
    image: rabbitmq:3.9.13-management
    container_name: producer_orchestration
    ports:
      - "5679:5672"
      - "15679:15672"
    networks:
      - private_network
  broker_queue:
    image: rabbitmq:3.9.13-management
    container_name: broker_queue
    hostname: broker_queue
    ports:
      - "5675:5672"
      - "15675:15672"
    networks:
      - private_network
  producer:
    build: ./producer/
    container_name: producer
    depends_on:
      - producer_orchestration_queue
      - broker_queue
    networks:
      - private_network
  broker:
    build: ./broker/
    container_name: broker
    depends_on:
      - broker_queue
    networks:
      - private_network
  # worker0:
  #   build: ./worker/
  #   container_name: worker0
  #   environment:
  #     EXECUTABLE: worker-1.0-SNAPSHOT-jar-with-dependencies.jar
  #     ID: 0
  #     REDIS_HOST: redis_db
  #     REDIS_PORT: 6379
  #     POLER: 0
  #     PRODUCER_QUEUE_HOST: broker_queue
  #     PRODUCER_QUEUE_PORT: 5672
  #   networks:
  #     - private_network
  # worker1:
  #   build: ./worker/
  #   container_name: worker1
  #   environment:
  #     EXECUTABLE: worker-1.0-SNAPSHOT-jar-with-dependencies.jar
  #     ID: 1
  #     REDIS_HOST: redis_db
  #     REDIS_PORT: 6379
  #     POLER: 0
  #     PRODUCER_QUEUE_HOST: broker_queue
  #     PRODUCER_QUEUE_PORT: 5672
  #   networks:
  #     - private_network
  # worker2:
  #   build: ./worker/
  #   container_name: worker2
  #   environment:
  #     EXECUTABLE: worker-1.0-SNAPSHOT-jar-with-dependencies.jar
  #     ID: 2
  #     REDIS_HOST: redis_db
  #     REDIS_PORT: 6379
  #     POLER: 0
  #     PRODUCER_QUEUE_HOST: broker_queue
  #     PRODUCER_QUEUE_PORT: 5672
  #   networks:
  #     - private_network
  worker0_queue:
    image: rabbitmq:3.9.13-management
    container_name: worker_queue0
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - private_network
  worker1_queue:
    image: rabbitmq:3.9.13-management
    container_name: worker_queue1
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - private_network
  worker2_queue:
    image: rabbitmq:3.9.13-management
    container_name: worker_queue2
    ports:
      - "5674:5672"
      - "15674:15672"
    networks:
      - private_network
  olt0_queue:
    image: rabbitmq:3.9.13-management
    container_name: olt0_queue
    ports:
      - "5676:5672"
      - "15676:15672"
    networks:
      - private_network
  olt1_queue:
    image: rabbitmq:3.9.13-management
    container_name: olt1_queue
    ports:
      - "5677:5672"
      - "15677:15672"
    networks:
      - private_network
  olt2_queue:
    image: rabbitmq:3.9.13-management
    container_name: olt2_queue
    ports:
      - "5678:5672"
      - "15678:15672"
    networks:
      - private_network
  redis_database:
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379"
    networks:
      - private_network
  results_database:
    image: redis:latest
    container_name: results
    ports:
      - "6380:6379"
    networks:
      - private_network
 
networks:
  private_network:
    driver: bridge
