version: "3"
services:
  broker_queue:
    image: rabbitmq:latest
    container_name: broker_queue
    ports:
      - "5675:5672"
      - "15675:15672"
  worker0_queue:
    image: rabbitmq:latest
    container_name: worker_queue0
    ports:
      - "5672:5672"
      - "15672:15672"
  worker1_queue:
    image: rabbitmq:latest
    container_name: worker_queue1
    ports:
      - "5673:5672"
      - "15673:15672"
  worker2_queue:
    image: rabbitmq:latest
    container_name: worker_queue2
    ports:
      - "5674:5672"
      - "15674:15672"
  redis_database:
    image: redis:latest
    container_name: redis_db
    ports:
      - "6379:6379"
