
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uservices_arch_testbench
  namespace: uservices_arch_testbench
spec:
  selector:
    matchLabels:
      app: uservices_arch_testbench
  replicas: 1
  template:
    metadata:
      labels:
        app: uservices_arch_testbench
    spec:
      containers:
      - name: run_orchestration
        image: registry/run_orchestration:1.0
        ports:
        - containerPort: 8000
          name: http-requests-port
      - name: producer_orchestration
        image: rabbitmq:3.9.13-managment
        ports:
        - containerPort: 5672
          name: queue-port
        - containerPort: 15672
          name: queue-management
      - name: producer
        image: registry/producer:1.0
      - name: broker
        image: registry/broker:1.0
      - name: broker_queue
        image: rabbitmq:3.9.13-managment
        ports:
        - containerPort: 5672
          name: queue-port
        - containerPort: 15672
          name: queue-management
      - name: worker0
        image: registry/worker:1.0
        args: ["0"]
      - name: worker1
        image: registry/worker:1.0
        args: ["1"]
      - name: worker2
        image: registry/worker:1.0
        args: ["2"]
      - name: worker0_queue
        image: rabbitmq:3.9.13-managment
        ports:
        - containerPort: 5672
          name: queue-port
        - containerPort: 15672
          name: queue-management
      - name: worker1_queue
        image: rabbitmq:3.9.13-managment
        ports:
        - containerPort: 5672
          name: queue-port
        - containerPort: 15672
          name: queue-management
      - name: worker2_queue
        image: rabbitmq:3.9.13-managment
        ports:
        - containerPort: 5672
          name: queue-port
        - containerPort: 15672
          name: queue-management
      - name: olt0
        image: registry/olt:1.0
        args: ["0"]
      - name: olt1
        image: registry/olt:1.0
        args: ["1"]
      - name: olt2
        image: registry/olt:1.0
        args: ["2"]
      - name: olt0_queue
        image: rabbitmq:3.9.13-managment
        ports:
        - containerPort: 5672
          name: queue-port
        - containerPort: 15672
          name: queue-management
      - name: olt1_queue
        image: rabbitmq:3.9.13-managment
        ports:
        - containerPort: 5672
          name: queue-port
        - containerPort: 15672
          name: queue-management
      - name: olt2_queue
        image: rabbitmq:3.9.13-managment
        ports:
        - containerPort: 5672
          name: queue-port
        - containerPort: 15672
          name: queue-management
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metada:
  name: uservices_arch_testbench_orchestrator
  namespace: dsr-onu-ztp
spec:
  selector:
    app: uservices_arch_testbench
  ports:
    - name: orchestrator_port
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32300 
  type: NodePort
