---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: onos-example-storage
  namespace: dsr-onu-ztp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
