# Relational Database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uservices-arch-testbench-results-relational-database
  namespace: dsr-onu-ztp
spec:
  selector:
    matchLabels:
      app: uservices-arch-testbench-results-relational-database
  replicas: 1
  template:
    metadata:
      labels:
        app: uservices-arch-testbench-results-relational-database
    spec:
      containers:
        - name: relational-db
          image: 10.112.106.236:32500/ztp-onu-relational_database:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
              name: results-port
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: relational-db
  namespace: dsr-onu-ztp
spec:
  selector:
    app: uservices-arch-testbench-results-relational-database
  ports:
    - name: relat-db-port
      port: 5432
      targetPort: 5432

# Componente: Producer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uservices-arch-testbench-producer
  namespace: dsr-onu-ztp
spec:
  selector:
    matchLabels:
      app: uservices-arch-testbench-producer
  replicas: 1
  template:
    metadata:
      labels:
        app: uservices-arch-testbench-producer
    spec:
      containers:
        - name: producer
          image: 10.112.106.236:32500/ztp-onu-producer_spring:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http-req-port
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: uservices-arch-testbench-producer
  namespace: dsr-onu-ztp
spec:
  selector:
    app: uservices-arch-testbench-producer
  ports:
    - name: producer-port
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32300
  type: NodePort

# Componente: Producer Queue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uservices-arch-testbench-producer-queue
  namespace: dsr-onu-ztp
spec:
  selector:
    matchLabels:
      app: uservices-arch-testbench-producer-queue
  replicas: 1
  template:
    metadata:
      labels:
        app: uservices-arch-testbench-producer-queue
    spec:
      containers:
        - name: producer-queue
          image: rabbitmq:3.9.13-management
          ports:
            - containerPort: 5672
              name: queue-port
            - containerPort: 15672
              name: queue-mngt
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: producer-queue
  namespace: dsr-onu-ztp
spec:
  selector:
    app: uservices-arch-testbench-producer-queue
  ports:
    - name: prod-queue-port
      port: 5672
      targetPort: 5672

# Componente: Broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uservices-arch-testbench-broker
  namespace: dsr-onu-ztp
spec:
  selector:
    matchLabels:
      app: uservices-arch-testbench-broker
  replicas: 1
  template:
    metadata:
      labels:
        app: uservices-arch-testbench-broker
    spec:
      containers:
        - name: broker
          image: 10.112.106.236:32500/ztp-onu-broker_spring:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: http-req-port
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: dsr-onu-ztp
spec:
  selector:
    app: uservices-arch-testbench-broker
  ports:
    - name: broker-port
      protocol: TCP
      port: 8081
      targetPort: 8081

# Componente: Broker Queue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uservices-arch-testbench-broker-queue
  namespace: dsr-onu-ztp
spec:
  selector:
    matchLabels:
      app: uservices-arch-testbench-broker-queue
  replicas: 1
  template:
    metadata:
      labels:
        app: uservices-arch-testbench-broker-queue
    spec:
      containers:
        - name: broker-queue
          image: rabbitmq:3.9.13-management
          ports:
            - containerPort: 5672
              name: queue-port
            - containerPort: 15672
              name: queue-mngt
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: broker-queue
  namespace: dsr-onu-ztp
spec:
  selector:
    app: uservices-arch-testbench-broker-queue
  ports:
    - name: broker-queue-port
      port: 5672
      targetPort: 5672

# Componente: Worker 0 bundle: worker + queue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uservices-arch-testbench-worker0-bundle
  namespace: dsr-onu-ztp
spec:
  selector:
    matchLabels:
      app: uservices-arch-testbench-worker0-bundle
  replicas: 1
  template:
    metadata:
      labels:
        app: uservices-arch-testbench-worker0-bundle
    spec:
      containers:
        - name: worker-0
          image: 10.112.106.236:32500/ztp-onu-worker_spring:1.0
          args:
            [
              "--server.port=8500",
              "--spring.rabbitmq.host=worker-queue-0",
              "--worker.id=0",
            ]
          imagePullPolicy: Always
          ports:
            - containerPort: 8500
              name: http-req-port
        - name: worker-queue-0
          image: rabbitmq:3.9.13-management
          ports:
            - containerPort: 5672
              name: queue-port
            - containerPort: 15672
              name: queue-mngt
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: worker-0
  namespace: dsr-onu-ztp
spec:
  selector:
    app: uservices-arch-testbench-worker0-bundle
  ports:
    - name: wk0-port
      port: 8500
      targetPort: 8500

---
apiVersion: v1
kind: Service
metadata:
  name: worker-queue-0
  namespace: dsr-onu-ztp
spec:
  selector:
    app: uservices-arch-testbench-worker0-bundle
  ports:
    - name: wk0-queue-port
      port: 5672
      targetPort: 5672

# Componente: Worker 1 bundle: worker + queue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uservices-arch-testbench-worker1-bundle
  namespace: dsr-onu-ztp
spec:
  selector:
    matchLabels:
      app: uservices-arch-testbench-worker1-bundle
  replicas: 1
  template:
    metadata:
      labels:
        app: uservices-arch-testbench-worker1-bundle
    spec:
      containers:
        - name: worker-1
          image: 10.112.106.236:32500/ztp-onu-worker_spring:1.0
          args:
            [
              "--server.port=8501",
              "--spring.rabbitmq.host=worker-queue-1",
              "--worker.id=1",
            ]
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
              name: http-req-port
        - name: worker-queue-1
          image: rabbitmq:3.9.13-management
          ports:
            - containerPort: 5672
              name: queue-port
            - containerPort: 15672
              name: queue-mngt
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: worker-1
  namespace: dsr-onu-ztp
spec:
  selector:
    app: uservices-arch-testbench-worker1-bundle
  ports:
    - name: wk1-port
      port: 8501
      targetPort: 8501

---
apiVersion: v1
kind: Service
metadata:
  name: worker-queue-1
  namespace: dsr-onu-ztp
spec:
  selector:
    app: uservices-arch-testbench-worker1-bundle
  ports:
    - name: wk1-queue-port
      port: 5672
      targetPort: 5672

# Componente: Worker 2 bundle: worker + queue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uservices-arch-testbench-worker2-bundle
  namespace: dsr-onu-ztp
spec:
  selector:
    matchLabels:
      app: uservices-arch-testbench-worker2-bundle
  replicas: 1
  template:
    metadata:
      labels:
        app: uservices-arch-testbench-worker2-bundle
    spec:
      containers:
        - name: worker-2
          image: 10.112.106.236:32500/ztp-onu-worker_spring:1.0
          args:
            [
              "--server.port=8502",
              "--spring.rabbitmq.host=worker-queue-2",
              "--worker.id=2",
            ]
          imagePullPolicy: Always
          ports:
            - containerPort: 8502
              name: http-req-port
        - name: worker-queue-2
          image: rabbitmq:3.9.13-management
          ports:
            - containerPort: 5672
              name: queue-port
            - containerPort: 15672
              name: queue-mngt
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: worker-2
  namespace: dsr-onu-ztp
spec:
  selector:
    app: uservices-arch-testbench-worker2-bundle
  ports:
    - name: wk2-port
      port: 8502
      targetPort: 8502

---
apiVersion: v1
kind: Service
metadata:
  name: worker-queue-2
  namespace: dsr-onu-ztp
spec:
  selector:
    app: uservices-arch-testbench-worker2-bundle
  ports:
    - name: wk2-queue-port
      port: 5672
      targetPort: 5672

# Componente: OLT 0 bundle: olt + queue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uservices-arch-testbench-olt0-bundle
  namespace: dsr-onu-ztp
spec:
  selector:
    matchLabels:
      app: uservices-arch-testbench-olt0-bundle
  replicas: 1
  template:
    metadata:
      labels:
        app: uservices-arch-testbench-olt0-bundle
    spec:
      containers:
        - name: olt-0
          image: 10.112.106.236:32500/ztp-onu-olt_spring:1.0
          args: ["--server.port=9000", "--spring.rabbitmq.host=olt-queue-0"]
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              name: http-req-port
        - name: olt-queue-0
          image: rabbitmq:3.9.13-management
          ports:
            - containerPort: 5672
              name: olt0-queue-port
            - containerPort: 15672
              name: olt0-queue-mngt
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: olt-0
  namespace: dsr-onu-ztp
spec:
  selector:
    app: uservices-arch-testbench-olt0-bundle
  ports:
    - name: olt0-port
      port: 9000
      targetPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: olt-queue-0
  namespace: dsr-onu-ztp
spec:
  selector:
    app: uservices-arch-testbench-olt0-bundle
  ports:
    - name: olt0-queue-port
      port: 5672
      targetPort: 5672

# Componente: OLT 1 bundle: olt + queue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uservices-arch-testbench-olt1-bundle
  namespace: dsr-onu-ztp
spec:
  selector:
    matchLabels:
      app: uservices-arch-testbench-olt1-bundle
  replicas: 1
  template:
    metadata:
      labels:
        app: uservices-arch-testbench-olt1-bundle
    spec:
      containers:
        - name: olt-1
          image: 10.112.106.236:32500/ztp-onu-olt_spring:1.0
          args: ["--server.port=9001", "--spring.rabbitmq.host=olt-queue-1"]
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
              name: http-req-port
        - name: olt-queue-1
          image: rabbitmq:3.9.13-management
          ports:
            - containerPort: 5672
              name: olt1-queue-port
            - containerPort: 15672
              name: olt1-queue-mngt
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: olt-1
  namespace: dsr-onu-ztp
spec:
  selector:
    app: uservices-arch-testbench-olt1-bundle
  ports:
    - name: olt1-port
      port: 9001
      targetPort: 9001

---
apiVersion: v1
kind: Service
metadata:
  name: olt-queue-1
  namespace: dsr-onu-ztp
spec:
  selector:
    app: uservices-arch-testbench-olt1-bundle
  ports:
    - name: olt1-queue-port
      port: 5672
      targetPort: 5672

# Componente: OLT 2 bundle: olt + queue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uservices-arch-testbench-olt2-bundle
  namespace: dsr-onu-ztp
spec:
  selector:
    matchLabels:
      app: uservices-arch-testbench-olt2-bundle
  replicas: 1
  template:
    metadata:
      labels:
        app: uservices-arch-testbench-olt2-bundle
    spec:
      containers:
        - name: olt-2
          image: 10.112.106.236:32500/ztp-onu-olt_spring:1.0
          args: ["--server.port=9002", "--spring.rabbitmq.host=olt-queue-2"]
          imagePullPolicy: Always
          ports:
            - containerPort: 9002
              name: http-req-port
        - name: olt-queue-2
          image: rabbitmq:3.9.13-management
          ports:
            - containerPort: 5672
              name: olt2-queue-port
            - containerPort: 15672
              name: olt2-queue-mngt
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: olt-2
  namespace: dsr-onu-ztp
spec:
  selector:
    app: uservices-arch-testbench-olt2-bundle
  ports:
    - name: olt2-port
      port: 9002
      targetPort: 9002

---
apiVersion: v1
kind: Service
metadata:
  name: olt-queue-2
  namespace: dsr-onu-ztp
spec:
  selector:
    app: uservices-arch-testbench-olt2-bundle
  ports:
    - name: olt2-queue-port
      port: 5672
      targetPort: 5672
