
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uservices-arch-testbench
  namespace: dsr-onu-ztp
spec:
  selector:
    matchLabels:
      app: uservices-arch-testbench
  replicas: 1
  template:
    metadata:
      labels:
        app: uservices-arch-testbench
    spec:
      containers:
      - name: run-orchestrator
        image: 10.112.106.236:32500/ztp-onu-run_orchestrator:1.0
        ports:
        - containerPort: 5000
          name: http-req-port
      - name: orch-queue
        image: rabbitmq:3.9.13-management
        ports:
        - containerPort: 5672
          name: queue-port
        - containerPort: 15672
          name: queue-mngt
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: uservices-arch-testbench-orchestrator
  namespace: dsr-onu-ztp
spec:
  selector:
    app: uservices-arch-testbench
  ports:
    - name: orch-port
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32300 
  type: NodePort
